"""
GEN-001 -- Stage 2: feature extraction for the 23 Phi-3.5-mini-instruct
`full_ai` essays generated by run_gen001_generate.py.

Reuses exp003a_extract_features.extract_features_for_essay unchanged --
the exact same 29-feature pipeline (23 stylometric + 6 LM-derived) used
for every essay in EXP-003A/B/C. No new features, no different
extraction logic -- only the input text differs.

Output: experiments/GEN-001/features_phi.jsonl
"""

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "backend"))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from exp003a_extract_features import extract_features_for_essay  # noqa: E402

SAMPLES_PATH = REPO_ROOT / "data" / "generated" / "GEN-001" / "samples.jsonl"
OUTPUT_PATH = REPO_ROOT / "experiments" / "GEN-001" / "features_phi.jsonl"


def main() -> None:
    with open(SAMPLES_PATH) as f:
        records = [json.loads(line) for line in f if line.strip()]
    print(f"Loaded {len(records)} GEN-001 samples.")

    passed = [r for r in records if r["qc_status"] == "passed"]
    flagged = [r for r in records if r["qc_status"] != "passed"]
    print(f"QC: {len(passed)} passed, {len(flagged)} flagged (flagged samples are still featurized -- excluded only at the evaluation stage if the approved methodology says so)")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    already_done = set()
    if OUTPUT_PATH.exists():
        with open(OUTPUT_PATH) as f:
            for line in f:
                if line.strip():
                    already_done.add(json.loads(line)["sample_id"])
        print(f"Resuming: {len(already_done)} already featurized")

    with open(OUTPUT_PATH, "a") as f:
        for i, r in enumerate(records):
            if r["sample_id"] in already_done:
                continue
            print(f"[{i+1}/{len(records)}] {r['sample_id']}")
            feats = extract_features_for_essay(r["text"])
            out = {
                "sample_id": r["sample_id"],
                "family_id": r["family_id"],
                "source_sample_id": r["source_sample_id"],
                "label": r["label"],
                "transformation_type": r["transformation_type"],
                "generation_model": r["generation_model"],
                "qc_status": r["qc_status"],
                "qc_notes": r["qc_notes"],
                **feats,
            }
            f.write(json.dumps(out) + "\n")
            f.flush()

    print(f"Done. Wrote features to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
